### PR TITLE
Issue/add readme

### LINKED ISSUE #55: update readme on how to use jackson integration
Currently there is no documentation about how to register arrow's jackson integration. e.g. users should be made aware that they need to register the arrow module using `mapper.registerArrowModule()`.

Might be useful to include this code in the top readme to make it immediately obvious.

```kotlin
val mapper = ObjectMapper()
    .registerKotlinModule()
    .registerArrowModule()
    .setSerializationInclusion(JsonInclude.Include.NON_ABSENT) // enable this to omit serialization of Option.None

data class Foo(val value: Option<String>)
data class Bar(val value: Nel<String>)

mapper.writeValueAsString(Foo(none())) // {}
mapper.readValue("{}", Foo::class.java) // Foo(value=Option.None)

mapper.writeValueAsString(Foo("foo".some())) // {"value":"foo"}
mapper.readValue("""{"value":"foo"}""", Foo::class.java) // Foo(value=Option.Some(foo))

mapper.writeValueAsString(Bar("bar".nel())) // {"value":["bar"]}
mapper.readValue("""{"value":["bar"]}""", Bar::class.java) // Bar(value=NonEmptyList(bar))
mapper.readValue("""{"value":[]}""", Bar::class.java) // IllegalArgumentException: NonEmptyList cannot be empty
```

### PR DESCRIPTION
**Pull request by myuwono**
fixes #55 

@rachelcarmena i'm still trying to figure out what's the general strategy around documentation in Arrow. PS: I noticed there's a docs module.

### CODE REVIEW

**Review by rachelcarmena — APPROVED** [review]
Thank you so much @myuwono !! :raised_hands: 

There are 3 steps involved with documentation:

1. Generate API documentation
    * Tool: [Dokka](https://github.com/Kotlin/dokka)
    * Gradle task: `dokka`
2. Validate code snippets included in the documentation (both static pages and generated API documentation):
    * Tool: [Ank](https://github.com/arrow-kt/arrow/blob/main/arrow-libs/ank/README.md)
    * Gradle task: `:arrow-docs:runAnk`
3. [Generate the website](https://github.com/arrow-kt/arrow/blob/main/CONTRIBUTING.md#how-to-run-the-website-in-your-local-workspace)

Why `arrow-docs`? Why another module to run the validation with Ank? Because Ank adds runtime dependencies so in this way it doesn't impact on required library dependencies.

However, there isn't a place in the website for Arrow Integrations right now, so let's keep it in the README file until then.

Thanks!! :clap:

**Comment by rachelcarmena** [comment]
@myuwono , Ank validation could be used for the code snippets in the README file meanwhile:

## `README.md`

```diff
-```kotlin 
+```kotlin:ank

(...)

-```kotlin 
+```kotlin:ank
```

##  `arrow-docs/build.gradle`

```diff
 dependencies {
-    compileOnly "io.arrow-kt:arrow-optics:$ARROW_VERSION"
-    compileOnly "io.arrow-kt:arrow-ui:$ARROW_VERSION"
-    compileOnly "io.arrow-kt:arrow-fx:$ARROW_VERSION"
-    compileOnly "io.arrow-kt:arrow-fx-rx2:$ARROW_VERSION"
-    compileOnly "io.arrow-kt:arrow-fx-reactor:$ARROW_VERSION"
-    compileOnly "io.arrow-kt:arrow-fx-kotlinx-coroutines:$ARROW_VERSION"
+    runtimeOnly project(':arrow-integrations-jackson-module')
 }

(...)

 ank {
-    source = file("${rootDir}/build/apidocs")
-    target = file("${rootDir}/build/_apidocs")
+    source = file("${rootDir}/build/documentation")
+    target = file("${rootDir}/build/_documentation")
     classpath = sourceSets.main.runtimeClasspath
 }
+
+task copyREADME(type: Copy) {
+    from "${rootDir}/README.md"
+    into "${rootDir}/build/documentation"
+}
+
+afterEvaluate {
+    runAnk.dependsOn 'copyREADME'
+    runAnk.mustRunAfter 'copyREADME'
+}
```

Then, run:

```
./gradlew :arrow-docs:runAnk
```

and errors will raise:
* Missing `import` statements.
* Missing dependencies in `arrow-docs/build.gradle` (`runtimeOnly` configuration).

In this way, we can ensure that the code snippets are up to date with the libraries.

**Comment by myuwono** [comment]
Thanks @rachelcarmena that works like a charm!! Ank is really awesome.

**Review by raulraja — APPROVED** [review]
thanks @myuwono !

**Pull request merged**
